---
- name: Main playbook that configures Linux and deploys chain repos
  hosts: all
  gather_facts: false
  roles:
    - base/update_apt
  # This is very very specific to how things were deployed. Keep? Remove?
    - role: base/bastion_ssh_only
      when: inventory_hostname in groups["baremetal_nodes"] and "'infra_bastion_hostname' in ansible_ssh_extra_args"
    - base/msmtp
    - role: base/docker
      tags:
        - docker
    - base/vimrc
    - base/set_hostname
    - role: base/dockerufw
      when: inventory_hostname in groups["baremetal_nodes"]
    - role: base/ufw
      when: inventory_hostname in groups["baremetal_nodes"]
    - base/upgrades
    - base/performance

  tasks:
    - name: Combine host and group repos into a single variable
      set_fact:
        repos: "{{ (group_repo_vars | default({})) | combine(host_repo_vars | default({}), recursive=true) }}"

    - name: Loop through repos and deploy
      include_role:
        name: apps/deployrepo
      loop: "{{ repos | dict2items }}"
      loop_control:
        loop_var: item
      vars:
        repo_name: "{{ item.key }}"
      when: repos is defined and repos | length > 0

# TODO - there was work to make this more idempotent, which has been lost. Could/should be recreated