---
- name: Set variables for {{ repo_name }}
  ansible.builtin.lineinfile:
    path: "~/{{ item.value.clone_dir }}/.env"
    regexp: '^{{ env_var.key }}='
    line: "{{ env_var.key }}={{ env_var.value }}"
  loop: "{{ item.value.env_variables | dict2items }}"
  loop_control:
    loop_var: env_var
  when: item.value.env_variables is defined

- name: update node software
  ansible.builtin.shell: ./ethd update
  args:
    chdir: ~/{{ item.value.clone_dir }}
    executable: /bin/bash
  register: update_output

- name: Result of ./ethd update
  debug:
    var: update_output.stdout_lines

# Switched to Alloy, adjust
#- name: Add tasks for custom-prom.yml and custom-lokiurl.yml
#  include_tasks: "../../base/custom_prometheus_loki/tasks/main.yml"
#  vars:
#    prometheus_template: "../../base/custom_prometheus_loki/templates/custom-prom.yml.j2"
#    promtail_template: "../../base/custom_prometheus_loki/templates/custom-lokiurl.yml.j2"
#    extra_prometheus_template: "../../base/custom_prometheus_loki/templates/extra-custom-prom.yml.j2"
#    extra_promtail_template: "../../base/custom_prometheus_loki/templates/extra-custom-lokiurl.yml.j2"

- name: restart changed software
  ansible.builtin.shell: ./ethd up
  args:
    chdir: ~/{{ item.value.clone_dir }}
    executable: /bin/bash
  register: up_output

- name: Result of ./ethd up stdout
  debug:
    var: up_output.stdout_lines

- name: Result of ./ethd up stderr
  debug:
    var: up_output.stderr_lines

- name: Read the .env file
  slurp:
    src: "~/{{ item.value.clone_dir }}/.env"
  register: env_file_content

- name: Decode the file content
  set_fact:
    env_file_text: "{{ env_file_content['content'] | b64decode }}"

- name: Extract COMPOSE_FILE line
  set_fact:
    compose_file_line: "{{ env_file_text | regex_search('^COMPOSE_FILE=.*$', multiline=True) }}"

- name: Wait for the Docker container to stabilize
  pause:
    seconds: "{{ '90' if 'ssv.yml' in compose_file_line else '30' }}"
  when:
    - compose_file_line is defined

- name: Get execution container info
  docker_container_info:
    name: "{{ item.value.clone_dir }}-execution-1" 
  register: execution_info

- name: Get consensus  container info
  docker_container_info:
    name: "{{ item.value.clone_dir }}-consensus-1"
  register: consensus_info

- name: Pretty-print consensus JSON
  shell: echo '{{ consensus_info | to_nice_json }}'
  register: consensus_json

- name: Print consensus info
  debug:
    msg: "{{ consensus_json.stdout }}"
    verbosity: 1

- name: Pretty-print execution JSON
  shell: echo '{{ execution_info | to_nice_json }}'
  register: execution_json

- name: Print execution info
  debug:
    msg: "{{ execution_json.stdout }}"
    verbosity: 1

- name: Fail if consensus or execution container is not running
  fail:
    msg: "Either consensus or execution is not running"
  when: >
    consensus_info.exists and
    (
      not consensus_info.container.State.Running or
      consensus_info.container.State.ExitCode != 0 or
      not execution_info.container.State.Running or
      execution_info.container.State.ExitCode != 0
    )

- name: Get version
  ansible.builtin.shell: ./ethd version
  args:
    chdir: ~/{{ item.value.clone_dir }}
    executable: /bin/bash
  register: version_output

- name: ./ethd version output
  debug:
    var: version_output.stdout_lines

#
#- name: Add extra prometheus scrape jobs
#  when: item.value.prom_extra_jobs is defined
#  loop: "{{ item.value.prom_extra_jobs | dict2items }}"
#  loop_control:
#    loop_var: scrape_item
#  ansible.builtin.template:
#    src: ../../base/custom_prometheus_loki/templates/custom-extra-scrape.yml.j2
#    dest: ~/{{ item.value.clone_dir }}/prometheus/file_sd/{{scrape_item.key}}.yml
