---
- name: Check if repo exists in ~/{{ item.value.clone_dir }}
  stat:
    path: "~/{{ item.value.clone_dir }}"
  register: clone_dir_stat

- name: Clone repo {{ repo_name }}
  ansible.builtin.git:
    repo: "{{ item.value.repo_url }}"
    dest: "~/{{ item.value.clone_dir }}"
    version: main
  when: not clone_dir_stat.stat.exists

- name: Install rsync
  apt:
    name:
    - rsync
    update_cache: yes
    cache_valid_time: 86400
  become: true
  when:
    - item.value.config_src is defined
    - not clone_dir_stat.stat.exists

- name: Synchronize config directory
  ansible.builtin.synchronize:
    src: "{{ item.value.config_src }}/"
    dest: "~/{{ item.value.clone_dir }}/config"
    use_ssh_args: yes
  when:
    - item.value.config_src is defined
    - not clone_dir_stat.stat.exists

- name: Check if .env file exists for {{ repo_name }}
  ansible.builtin.stat:
    path: "~/{{ item.value.clone_dir }}/.env"
  register: env_file_status

- name: Create .env file as needed for {{ repo_name }}
  ansible.builtin.copy:
    src: "~/{{ item.value.clone_dir }}/default.env"
    dest: "~/{{item.value.clone_dir }}/.env"
    remote_src: yes
  when: not env_file_status.stat.exists

- name: Set variables for {{ repo_name }}
  ansible.builtin.lineinfile:
    path: "~/{{ item.value.clone_dir }}/.env"
    regexp: '^{{ env_var.key }}='
    line: "{{ env_var.key }}={{ env_var.value }}"
  loop: "{{ item.value.env_variables | dict2items }}"
  loop_control:
    loop_var: env_var
  when: item.value.env_variables is defined

# Switched to Alloy, adjust
#- name: Add tasks for custom-prom.yml and custom-lokiurl.yml
#  include_tasks: "../../base/custom_prometheus_loki/tasks/main.yml"
#  vars:
#    prometheus_template: "../../base/custom_prometheus_loki/templates/custom-prom.yml.j2"
#    promtail_template: "../../base/custom_prometheus_loki/templates/custom-lokiurl.yml.j2"
#    extra_prometheus_template: "../../base/custom_prometheus_loki/templates/extra-custom-prom.yml.j2"
#    extra_promtail_template: "../../base/custom_prometheus_loki/templates/extra-custom-lokiurl.yml.j2"

- name: start node
  ansible.builtin.shell: ./ethd up
  args:
    chdir: ~/{{ item.value.clone_dir }}

- name: create dirk wallet
  ansible.builtin.shell: docker compose run --rm create-wallet && docker compose down && docker compose up -d && touch ~/{{ item.value.clone_dir }}/.wallet_created
  args:
    chdir: ~/{{ item.value.clone_dir }}
    creates: ~/{{ item.value.clone_dir }}/.wallet_created
  when:
    - not clone_dir_stat.stat.exists
    - repo_name == "dirk"

# Switched to Alloy, adjust
#- name: Add extra prometheus scrape jobs
#  when: item.value.prom_extra_jobs is defined
#  loop: "{{ item.value.prom_extra_jobs | dict2items }}"
#  loop_control:
#    loop_var: scrape_item
#  ansible.builtin.template:
#    src: ../../base/custom_prometheus_loki/templates/custom-extra-scrape.yml.j2
#    dest: ~/{{ item.value.clone_dir }}/prometheus/file_sd/{{scrape_item.key}}.yml
